### ISSUE TITLE
Feature Request: Allow specification of binary when calling mpi2prv

### ISSUE THREAD

**Issue by devreal** [bsc-performance-tools/extrae#16]
I am using Extrae (v3.5.4) on our Cray system. The `aprun` command copies the binary to a temporary directory on the respective node(s) and launches it from there, even if the working directory is shared. Because I am currently running my MPI application with only one process I have to run `mpi2prv` manually, which cannot find the binary in the temporary directory:

```
mpi2prv: Warning: Couldn't open /var/opt/cray/alps/spool/1666386/a.out for reading, addresses may not be translated.
```

It would be helpful to be able to specify the path to the original binary when invoking `mpi2prv` so that extrae can extract symbols from there. I did not see any command line option for this.

**Comment by gllort** [comment]
This feature is already available with the following command-line argument when invoking `mpi2prv`:

`mpi2prv -e <executable> ...`

Section 6.1.1 of the Extrae documentation (see link below [1]) shows further details of this and other options:

-e <BINARY>
Uses the given <BINARY> to translate addresses that are stored in the intermediate trace files into useful information (including function name, source file and line). The application has to be compiled with -g flag so as to obtain valuable information.

NOTE: Since Extrae version 2.4.0 this flag is superseded in Linux systems where /proc/self/maps is readable. The instrumentation part will annotate the binaries and shared libraries in use and will try to use them before using <BINARY>. This flag is still available in Linux systems as a default case just in case the binaries and libraries pointed by /proc/self/maps are not available.

[1] https://tools.bsc.es/sites/default/files/documentation/html/extrae/merge.html#paraver-merger

**Comment by devreal** [comment]
Thanks for the clarification. Indeed, I stumbled across the `-e` flag in the help output of `mpi2prv`, which says:

```
    -e file              Uses the executable file to obtain some information.
```

I guess `some information` was not specific enough to convince me that this is the right flag to use. Some clarification there would be helpful. I will consult the online documentation next time :)

**Comment by gllort** [comment]
Right, the command help is quite vague on this regard... to say the least! Duly noted, thanks! :)
